
// Wrapper to instantiate one custom tile for the flow to route.
// Generated by scripts/gen_custdiv.py --width 32 -- DONT edit by hand.
module custdiveg(
    // FPGA IOs (standard test IO harness)
    input wire [127:0] IN,
    output reg [127:0] OUT,
    input wire clk
);

// Test circuit IO wires
wire [31:0] A, B;
wire [31:0] O;
reg R0, R0_1;

// Assign to FPGA IO
assign A = IN[31:0];
assign B = IN[63:32];

always @(*) begin
    OUT[0] = R0_1;
    OUT[1] = R0;
    OUT[127:96] = O;
end

// Logic
custdiv #(
    .MODE_CUSTDIV(1)
) cdiv (
    .I0   (A[31:0]  ), //i
    .I1   (B[31:0]  ), //i
    .Q    (O        ), //o
    .C    (clk      ) //i
);

always @(posedge clk) begin
    R0_1 <= A[0];
    R0 <= R0_1;
end

endmodule
