/* Generated by Yosys 0.67+42 (git sha1 6f7123d1d-dirty, Release, Clang /usr/bin/clang++ 18.1.8) */

(* top =  1  *)
(* src = "/scratch/nhaldo/hft-efpga-ops/flow/custdiv_test/inputs/custdiv.v:4.1-41.10" *)
module custdiveg(IN, OUT, clk);
  (* src = "/scratch/nhaldo/hft-efpga-ops/flow/custdiv_test/inputs/custdiv.v:6.24-6.26" *)
  input [127:0] IN;
  wire [127:0] IN;
  (* src = "/scratch/nhaldo/hft-efpga-ops/flow/custdiv_test/inputs/custdiv.v:7.24-7.27" *)
  output [127:0] OUT;
  wire [127:0] OUT;
  (* src = "/scratch/nhaldo/hft-efpga-ops/flow/custdiv_test/inputs/custdiv.v:8.16-8.19" *)
  input clk;
  wire clk;
  (* src = "/scratch/nhaldo/hft-efpga-ops/flow/custdiv_test/inputs/custdiv.v:13.12-13.13" *)
  wire [7:0] O;
  (* src = "/scratch/nhaldo/hft-efpga-ops/flow/custdiv_test/inputs/custdiv.v:14.5-14.7" *)
  reg R0;
  (* src = "/scratch/nhaldo/hft-efpga-ops/flow/custdiv_test/inputs/custdiv.v:14.9-14.13" *)
  reg R0_1;
  (* src = "/scratch/nhaldo/hft-efpga-ops/flow/custdiv_test/inputs/custdiv.v:36.1-39.4" *)
  always @(posedge clk)
    R0 <= R0_1;
  (* src = "/scratch/nhaldo/hft-efpga-ops/flow/custdiv_test/inputs/custdiv.v:36.1-39.4" *)
  always @(posedge clk)
    R0_1 <= IN[0];
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/nhaldo/hft-efpga-ops/flow/custdiv_test/inputs/custdiv.v:29.3-34.2" *)
  custdiv #(
    .MODE_CUSTDIV(32'sd1)
  ) cdiv (
    .C(clk),
    .I0(IN[7:0]),
    .I1(IN[15:8]),
    .Q(O)
  );
  assign OUT = { O, 118'hxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx, R0, R0_1 };
endmodule
