#!/usr/bin/env python3
"""
Generate the custdiv tile at a given operand width.

3 files get written:
  arch/k4_N8_custdiv_<W>.xml (from arch/k4_N8_custdiv.xml.template)
  flow/custdiv_test/inputs/bbmodels.v (blackbox declarations for Yosys)
  flow/custdiv_test/inputs/custdiv.v (test wrapper)

Tile pin count = 3W + 1  (I0 + I1 + Q + clk).
Run: python3 scripts/gen_custdiv.py --width 32
"""

import argparse # parse --width 32 from command line
import sys # print to stderr
from pathlib import Path # make filesystem paths objects instead of str

#path constants
REPO = Path(__file__).resolve().parent.parent
TEMPLATE = REPO/"arch"/"k4_N8_custdiv.xml.template"
INPUTS = REPO/"flow"/"custdiv_test"/"inputs"

LOC_INDENT = " " * 10

# Unchanged by width. Copied verbatim from the original bbmodels.v.
CLBALU = """
module clbalu #(
    parameter MODE_ALU = 0
)(
    input wire [15:0] I1,
    input wire [15:0] I0,
    input wire [7:0] CTRL,
    input wire R,
    input wire CIN,
    input wire C,
    output wire COUT,
    output wire [15:0] Q
);
// MODE 0 - 32-bit pass through mode
// MODE 1 - add/sub
endmodule
"""

CUSTDIV_BB = """
module custdiv #(
    parameter MODE_CUSTDIV = 7
)(
    input wire [{wm1}:0] I1,
    input wire [{wm1}:0] I0,
    input wire C,
    output wire [{wm1}:0] Q
);
endmodule
"""

WRAPPER = """
// Wrapper to instantiate one custom tile for the flow to route.
// Generated by scripts/gen_custdiv.py --width {w} -- DONT edit by hand.
module custdiveg(
    // FPGA IOs (standard test IO harness)
    input wire [127:0] IN,
    output reg [127:0] OUT,
    input wire clk
);

// Test circuit IO wires
wire [{wm1}:0] A, B;
wire [{wm1}:0] O;
reg R0, R0_1;

// Assign to FPGA IO
assign A = IN[{wm1}:0];
assign B = IN[{b_hi}:{w}];

always @(*) begin
    OUT[0] = R0_1;
    OUT[1] = R0;
    OUT[127:{o_lo}] = O;
end

// Logic
custdiv #(
    .MODE_CUSTDIV(1)
) cdiv (
    .I0   (A[{wm1}:0]  ), //i
    .I1   (B[{wm1}:0]  ), //i
    .Q    (O        ), //o
    .C    (clk      ) //i
);

always @(posedge clk) begin
    R0_1 <= A[0];
    R0 <= R0_1;
end

endmodule
"""

def main():
    ap = argparse.ArgumentParser(description="Generate the custdiv tile at a given width.")
    ap.add_argument("--width", type=int, required=True, help="operand width in bits")
    args = ap.parse_args()

    w = args.width
    if w < 2:
        sys.exit(f"error: width must be >= 2, got {w}")
    if 2 * w > 128:
        sys.exit(f"error: width {w} needs IN[{2*w-1}:0] but the harness IN is only 128 bits "
                 f"(max width 64)")
    if not TEMPLATE.exists():
        sys.exit(f"error: template not found: {TEMPLATE}")

    wm1 = w - 1
    q_lo = (w + 1) // 2          # number of Q bits placed on the left side

    locs = [
        f'<loc side="right"> custdivtile.I0[{wm1}:0] custdivtile.clk </loc>',
        f'<loc side="top"> custdivtile.I1[{wm1}:0] </loc>',
        f'<loc side="left"> custdivtile.Q[{q_lo - 1}:0] </loc>',
        f'<loc side="bottom"> custdivtile.Q[{wm1}:{q_lo}] </loc>',
    ]
    counts = {"right": w + 1, "top": w, "left": q_lo, "bottom": w - q_lo}
    total = sum(counts.values())
    assert total == 3 * w + 1, f"pin count mismatch: {counts} sums to {total}, expected {3*w+1}"

    pinlocs = "\n".join(LOC_INDENT + line for line in locs)

    # Order matters: {WM1} before {W}, or {W} eats the "{W" inside "{WM1}".
    text = TEMPLATE.read_text()
    text = text.replace("{WM1}", str(wm1))
    text = text.replace("{PINLOCS}", pinlocs)
    text = text.replace("{W}", str(w))

    leftovers = [t for t in ("{W}", "{WM1}", "{PINLOCS}") if t in text]
    if leftovers:
        sys.exit(f"error: unsubstituted tokens remain in output: {leftovers}")

    arch_out = REPO / "arch" / f"k4_N8_custdiv_{w}.xml"
    arch_out.write_text(text)

    bb_out = INPUTS / "bbmodels.v"
    bb_out.write_text(CLBALU + CUSTDIV_BB.format(wm1=wm1))

    wrap_out = INPUTS / "custdiv.v"
    wrap_out.write_text(WRAPPER.format(w=w, wm1=wm1, b_hi=2 * w - 1, o_lo=128 - w))

    print(f"width = {w}   pins = {total}  "
          f"(right {counts['right']}, top {counts['top']}, "
          f"left {counts['left']}, bottom {counts['bottom']})")
    for p in (arch_out, bb_out, wrap_out):
        print(f"  wrote {p.relative_to(REPO)}")


if __name__ == "__main__":
    main()
